# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
# SPDX-License-Identifier: MIT
name: pypsa-eur
channels:
- conda-forge
- bioconda
- gurobi

dependencies:
- python>=3.8
- pip
- _libgcc_mutex==0.1
- _openmp_mutex==4.5
- alsa-lib==1.2.8
- ampl-mp==3.1.0
- amply==0.1.5
- aom==3.5.0
- atlite==0.2.10
- attr==2.5.1
- boost-cpp==1.78.0
# - build==1.0.0
- ca-certificates==2019.11.28
- cairo==1.16.0
- cartopy==0.21.1
- cdsapi==0.5.1
- cfitsio==4.2.0
- charls==2.4.1
- coin-or-cbc==2.10.8
- coin-or-cgl==0.60.6
- coin-or-clp==1.17.7
- coin-or-osi==0.108.7
- coincbc==2.10.8
- connection_pool==0.0.3
- country_converter==0.8.0
- curl==7.87.0
- dask==2023.1.0
- dask-core==2023.1.0
- dav1d==1.0.0
- descartes==1.1.0
- distributed==2023.1.0
- dpath==2.1.4
- entsoe-py==0.5.8
- expat==2.5.0
- fftw==3.3.10
- fiona==1.8.22
- fontconfig==2.14.1
- gdal==3.6.2
- geographiclib==1.52
- geojson-rewind==1.0.2
- geopandas==0.12.2
- geopandas-base==0.12.2
- geopy==2.3.0
- geos==3.11.1
- geotiff==1.7.1
- gettext==0.21.1
- glib==2.74.1
- glib-tools==2.74.1
- glpk==5.0
- gst-plugins-base==1.21.3
- gstreamer==1.21.3
- gstreamer-orc==0.4.33
- gurobi==9.5.2
- h5grove==1.2.0
- h5py==3.8.0
- harfbuzz==6.0.0
- hdf4==4.2.15
- hdf5==1.12.2
- icu==70.1
- imagecodecs==2023.1.23
- ipopt==3.14.11
- jack==1.9.21
- jupyterlab-h5web==6.6.1
- kealib==1.5.0
- keyutils==1.6.1
- krb5==1.20.1
- lcms2==2.14
- lerc==4.0.0
- libaec==1.0.6
- libavif==0.11.1
- libblas==3.9.0
- libcap==2.66
- libcblas==3.9.0
- libclang==15.0.7
- libclang13==15.0.7
- libcups==2.3.3
- libcurl==7.87.0
- libevent==2.1.10
- libflac==1.4.2
- libgcc-ng==12.2.0
- libgcrypt==1.10.1
- libgdal==3.6.2
- libgfortran-ng==12.2.0
- libgfortran5==12.2.0
- libglib==2.74.1
- libgomp==12.2.0
- libgpg-error==1.46
- libiconv==1.17
- libkml==1.3.0
- liblapack==3.9.0
- libllvm15==15.0.7
- libnetcdf==4.8.1
- libnghttp2==1.51.0
- libpq==15.1
- librttopo==1.1.0
- libsndfile==1.2.0
- libspatialite==5.0.1
- libsqlite==3.40.0
- libssh2==1.10.0
- libstdcxx-ng==12.2.0
- libsystemd0==252
- libtiff==4.5.0
- libtool==2.4.7
- libudev1==252
- libuuid==2.32.1
- libxcb==1.13
- libxkbcommon==1.0.3
- libxml2==2.10.3
- libxslt==1.1.37
- libzip==1.9.2
- libzlib==1.2.13
- linopy==0.1.5
- lxml==4.9.2
- markdown-it-py==3.0.0
- matplotlib==3.5.3
- matplotlib-base==3.5.3
# - mdurl==0.1.2
- memory_profiler==0.61.0
- mpg123==1.31.2
- mumps-include==5.2.1
- mumps-seq==5.2.1
- mysql-common==8.0.32
- mysql-libs==8.0.32
- netcdf4==1.6.2
- networkx==3.0
- nomkl==1.0
- nspr==4.35
- nss==3.82
- numexpr==2.8.3
- numpy==1.23.5
- openjpeg==2.5.0
- openpyxl==3.0.10
- pandas==1.5.3
- pcre2==10.40
- pip==22.3.1
- pkginfo==1.9.6
- postgresql==15.1
- powerplantmatching==0.5.5
- progressbar2==4.2.0
- proj==9.1.0
- pulp==2.7.0
- pulseaudio==16.1
- pycountry==22.3.5
- pygeos==0.14
- pyomo==6.4.4
- pyproj==3.4.1
# - pyproject-hooks==1.0.0
- pypsa==0.22.1
# - pypsatopo==0.9.0
- pyqt==5.15.7
- pyqt5-sip==12.11.0
- pyqtwebengine==5.15.7
- pytables==3.7.0
- python==3.10.8
- python_abi==3.10
- pytz==2022.7.1
- pyxlsb==1.0.10
- qt-main==5.15.6
- qt-webengine==5.15.4
- rasterio==1.3.4
# - readme-renderer==41.0
- requests-toolbelt==1.0.0
- reretry==0.11.8
- rfc3986==2.0.0
- rich==13.5.2
- rioxarray==0.0.23
- scipy==1.10.0
- scotch==6.0.9
- seaborn==0.12.2
- seaborn-base==0.12.2
- shapely==1.8.5
- sip==6.7.5
- snakemake-minimal==7.20.0
- stopit==1.1.2
- tabula-py==2.6.0
- throttler==1.2.1
- tiledb==2.13.2
- toposort==1.9
- tqdm==4.64.1
- twine==4.0.2
- tzcode==2022g
- xarray==2023.1.0
- xcb-util==0.4.0
- xcb-util-image==0.4.0
- xcb-util-keysyms==0.4.0
- xcb-util-renderutil==0.3.9
- xcb-util-wm==0.4.1
- xerces-c==3.2.4
- xlrd==2.0.1
- xorg-kbproto==1.0.7
- xorg-libice==1.0.10
- xorg-libsm==1.2.3
- xorg-libx11==1.7.2
- xorg-libxau==1.0.9
- xorg-libxdmcp==1.1.3
- xorg-libxext==1.3.4
- xorg-libxrender==0.9.10
- xorg-renderproto==0.11.1
- xorg-xextproto==7.3.0
- yaml==0.2.5
- yte==1.5.1
- zlib==1.2.13

- pip:
  - vresutils==0.3.1
  - tsam==2.2.2
  - countrycode==0.2
  - highspy==1.5.0.dev0
  - pybind11==2.10.3
